---
# - name: Setup hosts
#   hosts: all
#   become: true
#   gather_facts: true
#   roles:
#     - common
#   vars_files:
#     - "./vars/common.yaml"

- name: Start database
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - db
  vars_files:
    - "./vars/common.yaml"
  vars:
    tag_version: latest

- name: Start webserver and api
  hosts: all
  gather_facts: false
  become: false
  roles:
    - api
    - web
  vars_files:
    - "./vars/common.yaml"
  vars:
    - tag_version: v0.0.11
    - DB_URI: "mongodb://192.168.56.102:27017/"
    - SERVER_ADDRESS_WITH_TRAILING_SLASH: "http://ducpa_api:5000/"

- name: Start load balancer service
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - lb
  vars:
    - server_1: "192.168.56.102"
    - server_2: "192.168.56.101"
    - server_3: "localhost"
  vars_files:
    - "./vars/common.yaml"

- name: Start monitoring services
  hosts: all
  gather_facts: false
  become: false
  roles:
    - monitor
  vars:
    - remote_write_server: "http://192.168.56.102:9099/api/v1/write"
